name: Update Files (CoreConfigClass.cs)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'Docker/update.GitHubActions.sh'
      - 'DDTV_Core/SystemAssembly/ConfigModule/CoreConfigClass.cs'
      - '.github/workflows/Update_files_dependent_on_CoreConfigClass.cs.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: |
        mkdir ./tmp.d
        cp ./DDTV_Core/SystemAssembly/ConfigModule/CoreConfigClass.cs ./tmp.d/CoreConfigClass.cs
        chmod +x ./Docker/update.GitHubActions.sh && ./Docker/update.GitHubActions.sh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 更新依赖于CoreConfigClass.cs的文件
